CREATE TABLE address (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    number INTEGER NOT NULL CHECK (number >= 0),
    street TEXT NOT NULL,
    neighborhood TEXT NOT NULL
);

CREATE TABLE register (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name TEXT NOT NULL,
    social_name TEXT,
    cpf VARCHAR(11) NOT NULL,
    email TEXT NOT NULL,
    personal_phone VARCHAR(11) NOT NULL,
    personal_phone_has_whatsapp BOOLEAN NOT NULL,
    family_phone VARCHAR(11),
    address_id BIGINT NOT NULL UNIQUE REFERENCES address(id),
    gender VARCHAR(64) NOT NULL,
    education VARCHAR(64) NOT NULL,
    work_state VARCHAR(64) NOT NULL,
    course_of_interest TEXT NOT NULL,
    register_date DATE NOT NULL,
    CONSTRAINT uk_register_cpf UNIQUE (cpf),
    CONSTRAINT ck_register_cpf_length CHECK (CHAR_LENGTH(cpf) = 11)
);

CREATE TABLE register_disabilities (
    register_id BIGINT NOT NULL REFERENCES register(id),
    disability VARCHAR(64) NOT NULL,
    CONSTRAINT uk_register_disability UNIQUE (register_id, disability)
);
