CREATE TABLE address (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    number INTEGER NOT NULL CHECK (number >= 0),
    street TEXT NOT NULL,
    neighborhood TEXT NOT NULL
);

CREATE TABLE person (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name TEXT NOT NULL,
    social_name TEXT,
    cpf VARCHAR(11) NOT NULL,
    email TEXT NOT NULL,
    personal_phone VARCHAR(11) NOT NULL,
    personal_phone_has_whatsapp BOOLEAN NOT NULL,
    family_phone VARCHAR(11),
    address_id BIGINT NOT NULL UNIQUE REFERENCES address(id),
    gender VARCHAR(64) NOT NULL,
    education VARCHAR(64) NOT NULL,
    work_state VARCHAR(64) NOT NULL,
    CONSTRAINT uk_person_cpf UNIQUE (cpf),
    CONSTRAINT ck_person_cpf_length CHECK (CHAR_LENGTH(cpf) = 11)
);

CREATE TABLE person_disabilities (
    person_id BIGINT NOT NULL REFERENCES person(id),
    disability VARCHAR(64) NOT NULL,
    CONSTRAINT uk_person_disability UNIQUE (person_id, disability)
);

CREATE TABLE course (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    description VARCHAR(255),
    start DATE,
    finish DATE
);

CREATE TABLE register (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id BIGINT NOT NULL REFERENCES person(id),
    course_id BIGINT NOT NULL REFERENCES course(id),
    register_date DATE NOT NULL,
    CONSTRAINT uk_register_person_course UNIQUE (person_id, course_id)
);

CREATE TABLE course_class (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class_day DATE NOT NULL,
    session VARCHAR(255),
    start TIMESTAMP(6),
    finish TIMESTAMP(6),
    course_id BIGINT NOT NULL REFERENCES course(id),
    CONSTRAINT uk_course_class_course_day UNIQUE (course_id, class_day)
);

CREATE TABLE presence (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id BIGINT NOT NULL REFERENCES person(id),
    course_id BIGINT NOT NULL REFERENCES course(id),
    course_class_id BIGINT NOT NULL,
    status VARCHAR(255),
    CONSTRAINT fk_presence_course_class FOREIGN KEY (course_class_id) REFERENCES course_class(id),
    CONSTRAINT uk_presence_person_class UNIQUE (person_id, course_class_id)
);

CREATE INDEX idx_register_course ON register (course_id);
CREATE INDEX idx_course_class_course ON course_class (course_id);
CREATE INDEX idx_presence_person ON presence (person_id);
CREATE INDEX idx_presence_class_course ON presence (course_class_id, course_id);
