CREATE TABLE person (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name TEXT NOT NULL,
    social_name TEXT,
    cpf VARCHAR(11) NOT NULL,
    email TEXT NOT NULL,
    personal_phone VARCHAR(11) NOT NULL,
    personal_phone_has_whatsapp BOOLEAN NOT NULL,
    family_phone VARCHAR(11),
    address_id BIGINT NOT NULL UNIQUE REFERENCES address(id),
    gender VARCHAR(64) NOT NULL,
    education VARCHAR(64) NOT NULL,
    work_state VARCHAR(64) NOT NULL,
    CONSTRAINT uk_person_cpf UNIQUE (cpf),
    CONSTRAINT ck_person_cpf_length CHECK (CHAR_LENGTH(cpf) = 11)
);

-- Gerar IDs de pessoa independentemente dos IDs das inscrições existentes.
INSERT INTO person (full_name, social_name, cpf, email, personal_phone,
                    personal_phone_has_whatsapp, family_phone, address_id, gender, education, work_state)
SELECT full_name, social_name, cpf, email, personal_phone,
       personal_phone_has_whatsapp, family_phone, address_id, gender, education, work_state
FROM register;

ALTER TABLE register ADD COLUMN person_id BIGINT REFERENCES person(id);
UPDATE register SET person_id = (SELECT person.id FROM person WHERE person.cpf = register.cpf);
ALTER TABLE register ALTER COLUMN person_id SET NOT NULL;

CREATE TABLE person_disabilities (
    person_id BIGINT NOT NULL REFERENCES person(id),
    disability VARCHAR(64) NOT NULL,
    CONSTRAINT uk_person_disability UNIQUE (person_id, disability)
);

INSERT INTO person_disabilities (person_id, disability)
SELECT r.person_id, d.disability
FROM register_disabilities d JOIN register r ON r.id = d.register_id;

DROP TABLE register_disabilities;
ALTER TABLE register DROP CONSTRAINT uk_register_cpf;
ALTER TABLE register DROP CONSTRAINT ck_register_cpf_length;
ALTER TABLE register DROP COLUMN full_name;
ALTER TABLE register DROP COLUMN social_name;
ALTER TABLE register DROP COLUMN cpf;
ALTER TABLE register DROP COLUMN email;
ALTER TABLE register DROP COLUMN personal_phone;
ALTER TABLE register DROP COLUMN personal_phone_has_whatsapp;
ALTER TABLE register DROP COLUMN family_phone;
ALTER TABLE register DROP COLUMN address_id;
ALTER TABLE register DROP COLUMN gender;
ALTER TABLE register DROP COLUMN education;
ALTER TABLE register DROP COLUMN work_state;
ALTER TABLE register ADD CONSTRAINT uk_register_person_course UNIQUE (person_id, course_of_interest);
