CREATE TABLE course (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    description VARCHAR(255),
    start DATE,
    finish DATE
);

CREATE TABLE course_class (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class_day DATE,
    session VARCHAR(255),
    start TIMESTAMP(6),
    finish TIMESTAMP(6),
    course_id BIGINT REFERENCES course(id)
);

CREATE TABLE presence (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id BIGINT NOT NULL REFERENCES person(id),
    date DATE,
    course_id BIGINT NOT NULL REFERENCES course(id),
    status VARCHAR(255)
);

CREATE INDEX idx_course_class_course ON course_class (course_id);
CREATE INDEX idx_presence_person ON presence (person_id);
CREATE INDEX idx_presence_date_course ON presence (date, course_id);
